module ProjectEuler.Problems where

import           Common.Fibonacci               ( fibFast )
import qualified Common.Primes                 as P
import qualified Common.Helpers                as H
import qualified Safe                          as S

-- | Given an number sum the natural numbers that are multiples of 3 or 5 up to,
-- but not including the given number.
--
-- Problem 1 - Multiples of 3 and 5:
-- "If we list all the natural numbers below 10 that are multiples of 3 or 5, we
-- get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the
-- multiples of 3 or 5 below 1000."
sol1 :: Int -> Int
sol1 n = sum [ x | x <- [1 .. (n - 1)], x `rem` 3 == 0 || x `rem` 5 == 0 ]

-- | Problem 2 - Even Fibonacci numbers:
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.
sol2 :: Integer
sol2 = sum $ takeWhile (< 4000000) $ filter even $ fmap fibFast [0 ..]

-- | Problem 3 - Largest prime factor:
-- The prime factors of 13195 are 5, 7, 13 and 29.
-- What is the largest prime factor of the number 600851475143 ?
sol3 :: Maybe Int
sol3 = S.maximumMay $ P.primeFactors 600851475143

-- | Problem 4 - Largest palindrome product:
-- A palindromic number reads the same both ways. The largest palindrome made
-- from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest
-- palindrome made from the product of two 3-digit numbers.
sol4 :: Maybe Int
sol4 = S.maximumMay $ filter
  (\n -> n == H.reverseInt n)
  [ x * y | x <- [100 .. 999], y <- [100 .. x] ]

-- | Problem 5 - Smallest multiple
-- 2520 is the smallest number that can be divided by each of the numbers from 1
-- to 10 without any remainder. What is the smallest positive number that is
-- evenly divisible by all of the numbers from 1 to 20?
--
-- Note this is the first brute force thing I thought of. It works, but it's
-- very slow for large n.
sol5 :: Int -> Maybe Int
sol5 n =
  let divisors = [2..n]
  in  S.headMay $ filter (\x -> all (\d -> x `mod` d == 0) divisors) [n ..]

-- | Problem 6 - Sum square difference
-- The sum of the squares of the first ten natural numbers is:
--
--   (1^2 + 2^2 + .. + 10^2) = 385
--
-- The square of the sum of the first ten natural numbers is:
--
--   (1 + 2 + .. + 10)^2 = 55^2 = 3025
--
-- Hence the difference between the sum of the squares of the first ten natural
-- numbers and the square of the sum is
--
-- 3025 - 385 = 2640
--
-- Find the difference between the sum of the squares of the first one hundred
-- natural numbers and the square of the sum.
sol6 :: Integral a => a -> a
sol6 n =
  let square x = x * x
      nums         = [1 .. n]
      sumOfSquares = sum $ square <$> nums
      squareOfSum  = square $ sum nums
  in  squareOfSum - sumOfSquares

-- | Problem 7 - 10001st prime
-- By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see
-- that the 6th prime is 13.
-- What is the 10001st prime number?
sol7 :: Int -> Maybe Int
sol7 n = S.lastMay $ take n P.primes
