* Advent of Code (aoc) solutions

  In this directory I have solutions for [[https://adventofcode.com/][Advent of Code]] problems.

  The ~inputs~ directory has unmodified inputs for problems that I have solved.

* 2019 Day 1

   Original Puzzle: https://adventofcode.com/2019/day/1

   My rewrite of the requirements as I understand them.

** Part 1

   Fuel required to launch a given module is based on its mass. The fuel
   required is given by mass: ~f(m) = floor(m / 3) - 2~ where ~m~ is for mass.

   For example:

   #+begin_src
   f(12) = 2
   f(14) = 2
   f(1969) = 654
   f(100756) = 33583
   #+end_src

   What is the sum of the fuel requirements for all of the modules on your
   spacecraft?

** Part 2

   Include additional fuel for the fuel you just added. To calculate the fuel
   correctly repeatedly apply the calculation for the fuel of the fuel until it
   zero or negative.

   Find the total fuel for all the modules. For each module mass, calculate its
   fuel and add it to the total. Calculate the fuel requirements for each module
   separately, then add them all up at the end.

   For the following examples ~g(m)~ represents the new calculation function:

   #+begin_example
   g(14) = 2
   g(1969) = 654 + 216 + 70 + 21 + 5 = 966
   g(100756) = 33583 + 11192 + 3728 + 1240 + 411 + 135 + 43 + 12 + 2 = 50346.
   #+end_example

* 2019 Day 2

